#!/bin/bash
##https://github.com/nic-instruction/hello-nti-310/blob/master/automate.md
#GCloud
##TEST
##sudo su
tail -f /var/messages

#already has git installed
#Setup for final
git clone https://github.com/DFYT42/Linux-Automation-2/tree/master

#Create seven instances
##LOGSERVER##
gcloud compute instances create rsyslog-server2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform
##Not for first one: --metadata-from-file startup-script=/path/to/script.sh
gcloud compute instances create postgres-server2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform
--metadata-from-file startup-script=Linux-Automation-2/postgres.sh




