#!/bin/bash

yum install -y git
cd /tmp
git clone https://github.com/DFYT42/Linux-Automation-2

yum -y install openldap-servers openldap-clients

cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
#giving ownership from root to ldap bc ldap has to be owner of ldap daemon to get info
chown ldap. /var/lib/ldap/DB_CONFIG 

#ldap daemon
systemctl enable slapd
systemctl start slapd

#apache server
yum -y install httpd
yum -y install phpldapadmin

#Let's SELinux - know what is going on
#NSA to harden and secure Linux systems
#Apache connecct to ldap
setsebool -P httpd_can_connect_ldap on

systemctl enable httpd
syetmctl start httpd

#modifies our httpd.conf to access from external URL
sed -i 's,Require local,#Require local\n  Require all granted,g' /etc/httpd/conf.d/phpldapadmin.conf
unalias cp

#making backup in case something goes wrong
cp /etc/phpldapadmin/config.php /etc/phpldapadmin/config.php.orig

cp /tmp/DFYT42/Linux-Automation-2/config.php /etc/phpldapadmin/config.php
chown ldap:apache /etc/phpldapadmin/config.php

systemctl restart httpd.service

echo "phpldapadmin is now up and running"
echo "we are configuring ldap and ldap admin"

#Generates and stores new passwords & restricts only root user to read
newsecret=$(slappasswd -g)
newhash=$(slappasswd -s "$newsecret")
echo -n "$newsecret" > /root/ldap_admin_pass
chmod 0600 /root/ldap_admin_pass

#Becomes ldif and configures root domain
echo -e "dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcSuffix
olcSuffix: dc=nti310,dc=local
\n
dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcRootDN
olcRootDN: cn=ldapadm,dc=nti310,dc=local
\n
dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcRootPW
olcRootPW: $newhash" > db.ldif

ldapmodify -Y EXTERNAL  -H ldapi:/// -f db.ldif

#Auth restriction

echo 'dn: olcDatabase={1}monitor,cn=config
changetype: modify
replace: olcAccess
olcAccess: {0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external, cn=auth" read by dn.base="cn=ldapadm,dc=nti310,dc=local" read by * none' > monitor.ldif

ldapmodify -Y EXTERNAL -H ldapi:/// -f monitor.ldif

#Generates Certs
openssl req -new -x509 -nodes -out /etc/openldap/certs/nti310ldapcert.pem -keyout /etc/openldap/certs/nti310ldapkey.pem -days 365 -subj "/C=US/ST=WA/L=Seattle/O=SCC/OU=IT/CN=nti310.local"

chown -R ldap. /etc/openldap/certs/nti*.pem

##Error [root@ldap-b tmp]# ldapmodify -Y EXTERNAL  -H ldapi:/// -f certs.ldif
#SASL/EXTERNAL authentication started
#SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
#SASL SSF: 0
#modifying entry "cn=config"
#ldap_modify: Other (e.g., implementation specific) error (80)
echo -e "dn: cn=config
changetype: modify
replace: olcTLSCertificateFile
olcTLSCertificateFile: /etc/openldap/certs/nti310ldapcert.pem
\n
dn: cn=config
changetype: modify
replace: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: /etc/openldap/certs/nti310ldapkey.pem" > certs.ldif
 
ldapmodify -Y EXTERNAL  -H ldapi:/// -f certs.ldif

###Class Ends###
   64  vim certs.ldif 
   65  ldapmodify -Y EXTERNAL  -H ldapi:/// -f certs.ldif
   66  vim certs.ldif 
   67  ldapmodify -Y EXTERNAL  -H ldapi:/// -f certs.ldif
   68  rm certs.ldif 
   69  echo "dn: cn=config
   70  changetype: modify
   71  replace: olcTLSCertificateFile
   72  olcTLSCertificateFile: /etc/openldap/certs/nti310ldapcert.pem" > certs1.ldif
   73  echo "dn: cn=config
   74  changetype: modify
   75  replace: olcTLSCertificateKeyFile
   76  olcTLSCertificateKeyFile: /etc/openldap/certs/nti310ldapkey.pem" > certs2.ldif
   77  ldapmodify -Y EXTERNAL  -H ldapi:/// -f certs1.ldif
   78  ldapmodify -Y EXTERNAL  -H ldapi:/// -f certs2.ldif
   79  ldapmodify -Y EXTERNAL  -H ldapi:/// -f certs1.ldif
   80  slaptest -u
   81  unalias cp
   82  ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif 
   83  ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif 
   84  ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif 
   85  echo "dn: dc=nti310,dc=local
   86  dc: nti310
   87  objectClass: top
   88  objectClass: domain
   89  dn: cn=ldapadm ,dc=nti310,dc=local
   90  objectClass: organizationalRole
   91  cn: ldapadm
   92  description: LDAP Manager
   93  dn: ou=People,dc=nti310,dc=local
   94  objectClass: organizationalUnit
   95  ou: People
   96  dn: ou=Group,dc=nti310,dc=local
   97  objectClass: organizationalUnit
   98  ou: Group" > base.ldif
   99  ls
  100  vim base.ldif 
  101  ldapadd -x -W -D "cn=ldapadm,dc=nti310,dc=local" -f base.ldif
  102  vim /etc/httpd/conf.d/phpadmin.conf
  103  vim /etc/httpd/conf.d/phpldapadmin.conf
  104  systemctl restart httpd
  105  journalctl -xe
  106  vim /etc/httpd/conf.d/phpldapadmin.conf
  107  clear
  108  systemctl restart httpd
  109  vim /etc/httpd/conf.d/phpldapadmin.conf
  110  systemctl restart httpd
  111  tail -f /var/log
  112  tail -f /var/log/
  113  cd /var/log/
  114  ls
  115  cd httpd
  116  ls
  117  cat error_log 
   
