#!/bin/bash

#based on tutorial: https://www.tecmint.com/install-rsyslog-centralized-logging-in-centos-ubuntu/
#micro, CentOS7, standard 50GB, no http/https
#have postgres server up

#purpose: central location for server information/logs

sudo yum update -y && yum install -y rsyslog
#start the service for now, enable it to auto-start at boot and check it’s status
sudo systemctl start rsyslog
sudo systemctl enable rsyslog
#below not needed in automation
sudo systemctl status rsyslog

#make backup
cp /etc/rsyslog.conf /etc/rsyslog.conf.back
#edit
#To configure rsyslog as a network/central logging server, 
#you need to set the protocol (either UDP or TCP or both) it 
#will use for remote syslog reception as well as the port it listens on.
#sudo vim /etc/rsyslog.conf
sed -i 's/#$UDPServerRun 514/$UDPServerRun 514/g' /etc/rsyslog.conf
sed -i 's/#$InputTCPServerRun 514/$InputTCPServerRun 514/g' /etc/rsyslog.conf
