#!bin/bash
#micro/CentOS/Http&Https bc interacting with website
#pulling up backing for postgres Django server
#https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-centos-7

#Do not need bc installed, otherwise needed for next: sudo yum install epel-release
#install packages gcc=gnu compiler
yum -y install python-pip python-devel gcc postgresql-server postgresql-devel postgresql-contrib
#initialize postgres
postgresql-setup initdb
#start postgres
systemctl start postgresql
#need to edit config file authentication mode to md5
vim /var/lib/pgsql/data/pg_hba.conf
sed -i 's,host    all             all             127.0.0.1/32            ident,host    all             all             127.0.0.1/32            md5,g' /var/lib/pgsql/data/pg_hba.conf
sed -i 's,host    all             all             ::1/128                 ident,host    all             all             ::1/128                 md5,g' /var/lib/pgsql/data/pg_hba.conf
#Restart PostGres service
systemctl restart postgresql
#enable PostGres service
systemctl enable postgresql

#change to postgres admin user that was created during install to run postgres
sudo su -postgres
#shell in as postgres user
psql
